import { EhrMappingRepository } from "../../../domain/ports/EhrMappingRepository";
import { EhrMappingModel } from "../models/EhrMappingModel";
import { EhrMapping } from "../../../domain/entities/EhrMapping";

/**
 * 🏗️ EhrMappingRepositoryImpl - Implementation of EhrMappingRepository
 *
 * This class is responsible for handling the persistence of `EhrMapping` entities.
 * It acts as an **adapter** in the Hexagonal Architecture, bridging the gap between
 * the domain layer and the infrastructure layer (database).
 *
 * 🏛️ **Role in Hexagonal Architecture:**
 * - 🎯 **Infrastructure Layer (Adapter):** Implements the `EhrMappingRepository` interface.
 * - 🔌 **Port Implementation:** Acts as a concrete repository for database operations.
 * - 🗄 **Persistence Handling:** Uses `EhrMappingModel` (ORM) to store and retrieve data.
 * - 🚀 **Decoupling:** Keeps the domain logic clean by isolating database-specific details.
 */
export class EhrMappingRepositoryImpl implements EhrMappingRepository {
  /**
   * 📝 Creates a new EHR mapping entry in the database.
   *
   * @param {Omit<EhrMapping, "id">} ehrMapping - The EHR mapping data excluding the ID (generated by DB).
   * @returns {Promise<EhrMapping>} - The created `EhrMapping` entity with an assigned ID.
   *
   * 🔹 **Responsibilities:**
   * - Receives an `EhrMapping` object without an ID.
   * - Uses `EhrMappingModel` (ORM) to persist the entity.
   * - Returns the stored entity with an assigned ID.
   */
  async create(ehrMapping: Omit<EhrMapping, "id">): Promise<EhrMapping> {
    const result = await EhrMappingModel.create(ehrMapping);
    return new EhrMapping(
      result.id,
      result.ehr_name,
      result.question_key,
      result.ehr_field,
      // result.created_at,
      // result.updated_at
    );
  }
}
